version: '3.9'

services:
  db:
    image: postgres:15
    container_name: journey_db
    environment:
      POSTGRES_USER: journeymate_bbdd
      POSTGRES_PASSWORD: journeymate-bbdd
      POSTGRES_DB: journeymate_bbdd
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    image: journeymate_backend
    container_name: journey_backend
    depends_on:
      - db
    environment:
      # Conexi√≥n a la DB interna de Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/journeymate_bbdd
      SPRING_DATASOURCE_USERNAME: journeymate_bbdd
      SPRING_DATASOURCE_PASSWORD: journeymate-bbdd
      # Claves seguras (se leen del archivo .env)
      RAPIDAPI_KEY: ${RAPIDAPI_KEY}
      GOOGLE_MAPS_KEY: ${GOOGLE_MAPS_KEY}
      GOOGLE_AI_KEY: ${GOOGLE_AI_KEY}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_SECRET: ${PAYPAL_SECRET}
    ports:
      - "8080:8080"

volumes:
  postgres_data: